networks:
  paulonet:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24

services:
  nginx:
    image: nginx:latest
    networks:
      paulonet:
        ipv4_address: 172.20.0.100
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - vendas
      - juridico

  vendas:
    build: 
      context: ./vendas
      dockerfile: Dockerfile.Vendas
    networks:
      paulonet:
        ipv4_address: 172.20.0.120
    restart: on-failure

  juridico:
    build: 
      context: ./juridico
      dockerfile: Dockerfile.Juridico
    networks:
      paulonet:
        ipv4_address: 172.20.0.130
    restart: on-failure 
